# Generated by Django 5.2.15 on 2026-06-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('content_type', models.CharField(max_length=128)),
                ('serializer_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mockvendor_format',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='POST', max_length=10)),
                ('path_pattern', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('default_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockvendor.format')),
            ],
            options={
                'db_table': 'mockvendor_endpoint',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.IntegerField(default=0)),
                ('is_sequence', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('match_key', models.CharField(blank=True, max_length=120)),
                ('match_value', models.CharField(blank=True, max_length=255)),
                ('seq_cursor', models.IntegerField(default=0)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='mockvendor.endpoint')),
            ],
            options={
                'db_table': 'mockvendor_scenario',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_index', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('canonical', models.JSONField(blank=True, null=True)),
                ('raw_override', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('delay_ms', models.IntegerField(default=0)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockvendor.format')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockvendor.scenario')),
            ],
            options={
                'db_table': 'mockvendor_response',
                'ordering': ['seq_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(db_index=True, max_length=255)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('delay_applied_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockvendor.endpoint')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockvendor.scenario')),
            ],
            options={
                'db_table': 'mockvendor_calllog',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['method', 'path_pattern'], name='mockvendor__method_d7a8bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('method', 'path_pattern')},
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['endpoint', 'priority'], name='mockvendor__endpoin_7ec00a_idx'),
        ),
    ]
