# Generated by Django 5.2.15 on 2026-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='response_body',
            field=models.TextField(blank=True),
        ),
    ]
