# Generated by Django 5.2.15 on 2026-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvendor', '0002_add_calllog_response_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(max_length=120, unique=True)),
                ('definition', models.JSONField()),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mockvendor_scenariobundle',
            },
        ),
    ]
