# Generated by Django 5.2.15 on 2026-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvendor', '0005_testrun_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='case_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testrun',
            name='source',
            field=models.CharField(default='csv', max_length=8),
        ),
        migrations.AddField(
            model_name='testrun',
            name='suite',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='csv_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=120)),
                ('suite', models.CharField(blank=True, db_index=True, max_length=120)),
                ('definition', models.JSONField(default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mockvendor_testcase',
                'ordering': ['suite', 'case_id'],
                'unique_together': {('suite', 'case_id')},
            },
        ),
    ]
