# Generated by Django 5.2.15 on 2026-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvendor', '0006_testcase_and_run_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
