# Generated by Django 5.2.15 on 2026-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=120, unique=True)),
                ('bright_uid', models.CharField(blank=True, max_length=120)),
                ('test_path', models.CharField(blank=True, max_length=120)),
                ('decision', models.CharField(default='PENDING', max_length=20)),
                ('persona_inquiry_id', models.CharField(blank=True, max_length=120, null=True)),
                ('escalation_type', models.CharField(blank=True, max_length=40)),
                ('escalation_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
    ]
